Failure # 1 (occurred at 2021-07-26_14-42-39)
Traceback (most recent call last):
  File "/net/work/almosova/rl_venv/lib64/python3.6/site-packages/ray/tune/trial_runner.py", line 718, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/net/work/almosova/rl_venv/lib64/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 688, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/net/work/almosova/rl_venv/lib64/python3.6/site-packages/ray/_private/client_mode_hook.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "/net/work/almosova/rl_venv/lib64/python3.6/site-packages/ray/worker.py", line 1495, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AssertionError): [36mray::PPO.train_buffered()[39m (pid=13670, ip=10.9.5.62)
  File "python/ray/_raylet.pyx", line 501, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 451, in ray._raylet.execute_task.function_executor
  File "/net/work/almosova/rl_venv/lib64/python3.6/site-packages/ray/_private/function_manager.py", line 563, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/net/work/almosova/rl_venv/lib64/python3.6/site-packages/ray/tune/trainable.py", line 173, in train_buffered
    result = self.train()
  File "/net/work/almosova/rl_venv/lib64/python3.6/site-packages/ray/rllib/agents/trainer.py", line 605, in train
    raise e
  File "/net/work/almosova/rl_venv/lib64/python3.6/site-packages/ray/rllib/agents/trainer.py", line 594, in train
    result = Trainable.train(self)
  File "/net/work/almosova/rl_venv/lib64/python3.6/site-packages/ray/tune/trainable.py", line 232, in train
    result = self.step()
  File "/net/work/almosova/rl_venv/lib64/python3.6/site-packages/ray/rllib/agents/trainer_template.py", line 173, in step
    res = next(self.train_exec_impl)
  File "/net/work/almosova/rl_venv/lib64/python3.6/site-packages/ray/util/iter.py", line 756, in __next__
    return next(self.built_iterator)
  File "/net/work/almosova/rl_venv/lib64/python3.6/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/net/work/almosova/rl_venv/lib64/python3.6/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/net/work/almosova/rl_venv/lib64/python3.6/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/net/work/almosova/rl_venv/lib64/python3.6/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/net/work/almosova/rl_venv/lib64/python3.6/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/net/work/almosova/rl_venv/lib64/python3.6/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/net/work/almosova/rl_venv/lib64/python3.6/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  [Previous line repeated 1 more time]
  File "/net/work/almosova/rl_venv/lib64/python3.6/site-packages/ray/util/iter.py", line 876, in apply_flatten
    for item in it:
  File "/net/work/almosova/rl_venv/lib64/python3.6/site-packages/ray/util/iter.py", line 828, in add_wait_hooks
    item = next(it)
  File "/net/work/almosova/rl_venv/lib64/python3.6/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/net/work/almosova/rl_venv/lib64/python3.6/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/net/work/almosova/rl_venv/lib64/python3.6/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  [Previous line repeated 1 more time]
  File "/net/work/almosova/rl_venv/lib64/python3.6/site-packages/ray/util/iter.py", line 471, in base_iterator
    yield ray.get(futures, timeout=timeout)
  File "/net/work/almosova/rl_venv/lib64/python3.6/site-packages/ray/_private/client_mode_hook.py", line 62, in wrapper
    return func(*args, **kwargs)
ray.exceptions.RayTaskError(AssertionError): [36mray::RolloutWorker.par_iter_next()[39m (pid=13669, ip=10.9.5.62)
  File "python/ray/_raylet.pyx", line 501, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 451, in ray._raylet.execute_task.function_executor
  File "/net/work/almosova/rl_venv/lib64/python3.6/site-packages/ray/_private/function_manager.py", line 563, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/net/work/almosova/rl_venv/lib64/python3.6/site-packages/ray/util/iter.py", line 1151, in par_iter_next
    return next(self.local_it)
  File "/net/work/almosova/rl_venv/lib64/python3.6/site-packages/ray/rllib/evaluation/rollout_worker.py", line 333, in gen_rollouts
    yield self.sample()
  File "/net/work/almosova/rl_venv/lib64/python3.6/site-packages/ray/rllib/evaluation/rollout_worker.py", line 726, in sample
    batches = [self.input_reader.next()]
  File "/net/work/almosova/rl_venv/lib64/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 99, in next
    batches = [self.get_data()]
  File "/net/work/almosova/rl_venv/lib64/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 226, in get_data
    item = next(self.rollout_provider)
  File "/net/work/almosova/rl_venv/lib64/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 651, in _env_runner
    base_env.send_actions(actions_to_send)
  File "/net/work/almosova/rl_venv/lib64/python3.6/site-packages/ray/rllib/env/base_env.py", line 421, in send_actions
    obs, rewards, dones, infos = env.step(agent_dict)
  File "/net/homes/ivw/almosova/NK_1/human_friction/rllib/rllib_env.py", line 40, in step
    obs, r, done, info = self.env.step(actions)
  File "/net/homes/ivw/almosova/NK_1/human_friction/environment/new_keynes.py", line 169, in step
    obs = self.generate_observations(actions)
  File "/net/homes/ivw/almosova/NK_1/human_friction/environment/new_keynes.py", line 196, in generate_observations
    self.clear_labor_market(wages)
  File "/net/homes/ivw/almosova/NK_1/human_friction/environment/new_keynes.py", line 241, in clear_labor_market
    agent.earn(occupation[agent.agent_id], wages[agent.agent_id])
  File "/net/homes/ivw/almosova/NK_1/human_friction/agents/household.py", line 22, in earn
    assert wage >= 0.0
AssertionError

